table view_uk_youtubers
	lineageTag: a2808558-26c8-4a79-b731-f40cf83f2694

	measure 'Total Subscribers (Million)' = DIVIDE(SUM(view_uk_youtubers[subscriber_count]), 1000000)
		lineageTag: a9657ba8-169f-47d9-b0b2-b11870f0ad1b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Views (Billion)' = DIVIDE(SUM(view_uk_youtubers[view_count]), 1000000000)
		lineageTag: fa164a28-9d6a-480f-b6cb-6040bc22728e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Subscriber Engagement' =
			
			DIVIDE(
				SUM('view_uk_youtubers'[subscriber_count]),
				SUM('view_uk_youtubers'[video_count])
			)
		formatString: 0.00
		lineageTag: 3f47547f-84ad-4bf6-af62-3dca24fea5ed

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	measure 'Views per Subscriber' =
			
			DIVIDE(
				SUM('view_uk_youtubers'[view_count]),
				SUM('view_uk_youtubers'[subscriber_count])
			)
		formatString: 0.00
		lineageTag: 0fab2840-4c95-4c0f-a291-a02f93b569e2

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	measure 'Average Views per Video (Million)' =
			
			DIVIDE(
				SUM('view_uk_youtubers'[view_count]),
				SUM('view_uk_youtubers'[video_count]) * 1000000
			)
		formatString: 0
		lineageTag: 2c32981d-a47e-4a0e-b7d3-bb740e05d400

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MathematicalDivision"
				}

		changedProperty = FormatString

	column channel_name
		dataType: string
		lineageTag: 01ca3c3e-c66a-4a03-8837-58ac859421ca
		summarizeBy: none
		sourceColumn: channel_name

		annotation SummarizationSetBy = Automatic

	column subscriber_count
		dataType: int64
		formatString: 0
		lineageTag: 0f95a310-4bf3-40d2-b88e-e35294538282
		summarizeBy: sum
		sourceColumn: subscriber_count

		annotation SummarizationSetBy = Automatic

	column view_count
		dataType: int64
		formatString: 0
		lineageTag: 8d988118-6080-4538-91f9-351f3cdc78e7
		summarizeBy: sum
		sourceColumn: view_count

		annotation SummarizationSetBy = Automatic

	column video_count
		dataType: int64
		formatString: 0
		lineageTag: 4a6a19c7-f64a-4e5b-b58e-98e15770e403
		summarizeBy: sum
		sourceColumn: video_count

		annotation SummarizationSetBy = Automatic

	partition view_uk_youtubers = m
		mode: import
		source =
				let
				    Source = Sql.Database("MSI\SQLEXPRESS", "youtube_uk_db"),
				    dbo_view_uk_youtubers = Source{[Schema="dbo",Item="view_uk_youtubers"]}[Data]
				in
				    dbo_view_uk_youtubers

	annotation PBI_ResultType = Table

